config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  # get 'pages/hello'
  root 'pages#hello'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy, :show]
  # GET /friends or /friends.json
  def index
    @friends = current_user.friends.all
    if params[:search].present?
      @friends = @friends.where("LOWER(REPLACE(first_name || ' ' || last_name, '\s+', ' ')) LIKE LOWER(?)", "%#{params[:search].squish.downcase}%")
  end
end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)

    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friends_url, notice: "Friend was successfully created." }
        format.json { render :index, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friends_url, notice: "Friend was successfully updated." }
        format.json { render :index, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not authorized to edit this friend" if @friend.nil?
  end
   
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :emai, :phone, :twitter, :user_id, :instagram, :snapchat, :facebook)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def hello
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div class="error-message">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :emai %>
    <%= form.text_field :emai, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :twitter %>
    <%= form.text_field :twitter, class: "form-control" %>
  </div>

    <div class="form-group">
    <%= form.label :instagram %>
    <%= form.text_field :instagram, class: "form-control" %>
  </div>

    <div class="form-group">
    <%= form.label :facebook %>
    <%= form.text_field :facebook, class: "form-control" %>
  </div>

    <div class="form-group">
    <%= form.label :snapchat %>
    <%= form.text_field :snapchat, class: "form-control" %>
  </div>

  <%= form.number_field :user_id, id: :friend_user_id, value: current_user.id, type: :hidden %>

  <div class="form-group">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

<style>
form {
  max-width: 500px;
  margin: 0 auto;
  padding: 20px;
  border: 1px solid #ddd;
  border-radius: 5px;
}

.form-group {
  margin-bottom: 20px;
}

label {
  display: block;
  margin-bottom: 5px;
  font-weight: bold;
}

input[type="text"], input[type="email"], input[type="tel"], input[type="number"] {
  display: block;
  width: 95%;
  padding: 10px;
  border: 1px solid #ddd;
  border-radius: 5px;
}

input[type="submit"] {
  display: inline-block;
  padding: 10px 20px;
  background-color: #007bff;
  color: #fff;
  border: none;
  border-radius: 5px;
  cursor: pointer;
  transition: background-color 0.2s ease-in-out;
}

input[type="submit"]:hover {
  background-color: #0069d9;
}

</style>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>" class="info" >
  <h6>
    <%= friend.first_name + ' ' +  friend.last_name %>
  </h6>

  <p>
    <%= friend.phone %>
  </p>
</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<style>
h1 {
  text-align: center;
  margin: 10px;
}
</style>

app/views/friends/index.html.erb
<div class="search">
      <%= form_tag friends_path, method: :get do %>
      <%= text_field_tag :search, params[:search], class: "search_input", placeholder: "Search for friend" %>
        <%= submit_tag "Search", class: 'search_button' %>
        <% if params[:search].present? %>
          <%= button_tag "Cancel", type: :reset, class: 'search_button', onclick: "location.href='#{friends_path}'" %>
        <% end %>
      <% end %>
</div>

<% if @friends.any? %>
<div class="container main_container">
  <div class= "col">
  <% @friends.each_with_index do |friend, index| %>
   <%= link_to friend_path(friend) do %>    
     <div class= "row"> 
        <div class= "circle">
          <%= index + 1 %>
        </div>
        <%= render friend %>
     </div>
    <% end %>
  <% end %>
  </div>
</div>
<% else %>
  <p>No friends found.</p>
<% end %>

<div class="add_friends">
<%= link_to "+", new_friend_path %>
</div>

app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render "form", friend: @friend %>

<style>
h1 {
  text-align: center;
  margin: 10px;
}
</style>

app/views/friends/show.html.erb
<style>
  .show-container {
    max-width: 800px;
    margin: 0 auto;
    padding: 30px;
    border: 1px solid #e5e5e5;
    border-radius: 10px;
    background-color: #fff;
    box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
  }

  .show-header {
    font-size: 32px;
    font-weight: 600;
    text-align: center;
    margin-bottom: 30px;
    color: #333;
  }

  .show-info {
    display: flex;
    flex-wrap: wrap;
    gap: 20px;
    margin-bottom: 30px;
  }

  .show-info p {
    margin: 0;
    font-size: 18px;
    font-weight: 400;
    color: #555;
  }

  .show-info p strong {
    font-weight: 600;
    color: #333;
  }

  .action {
    display: flex;
    justify-content: flex-end;
    gap: 20px;
  }

  .action a {
    padding: 10px 20px;
    border: 1px solid #e5e5e5;
    border-radius: 5px;
    font-size: 16px;
    font-weight: 500;
    text-decoration: none;
    color: #333;
    transition: background-color 0.3s ease-in-out;
  }

  .action a:hover {
    background-color: #f5f5f5;
  }

  .action button {
    padding: 10px 20px;
    border: none;
    border-radius: 5px;
    font-size: 16px;
    font-weight: 500;
    background-color: #dc3545;
    color: #fff;
    cursor: pointer;
    transition: background-color 0.3s ease-in-out;
  }

  .action button:hover {
    background-color: #c82333;
  }

  @media screen and (max-width: 768px) {
    .show-info {
      flex-direction: column;
      gap: 10px;
    }

    .show-info p {
      font-size: 16px;
    }

    .action {
      flex-direction: column;
      justify-content: center;
      gap: 10px;
    }

    .action a,
    .action button {
      width: 90%;
      text-align: center;
    }
  }
</style>

<div class="show-container">
  <div class="show-header">
    <%= @friend.first_name + ' ' + @friend.last_name %>
  </div>

  <div class="show-info">
    <p><strong>Phone:</strong> <%= @friend.phone %></p>
    <p><strong>Twitter:</strong> <%= @friend.twitter %></p>
    <p><strong>Instagram:</strong> <%= @friend.instagram %></p>
    <p><strong>Facebook:</strong> <%= @friend.facebook %></p>
    <p><strong>Snapchat:</strong> <%= @friend.snapchat %></p>
    <p><strong>Email:</strong> <%= @friend.emai %></p>
  </div>

  <div class="action">
    <%= link_to "Edit", edit_friend_path(@friend) %>
    <%= link_to "Back", friends_path %>
    <%= button_to "Destroy", @friend, method: :delete, data: { confirm: "Are you sure?" } %>
  </div>
</div>

app/views/layouts/_alert.html.erb
<div class='alert'>
  <h1><%= notice %></h1>
</div>

<script>
  setTimeout(function() {
    document.querySelector('.alert').style.display = 'none';
  }, 3000);
</script>

app/views/layouts/_header.html.erb
<div class="header">
  <div class="header_title">
    <h1><%= link_to 'Friends App', root_path %></h1>
  </div>
  <nav>
    <ul class="nav-links">
      <% if user_signed_in? %>
        <li><%= link_to 'Friends', friends_path %></li>
        <li><%= link_to "Profile", edit_user_registration_path %></li>
        <li><%= link_to "SignOut", destroy_user_session_path, 'data-turbo-method': :delete, class:"nav-link" %></li>
      <% else %>
        <li><%= link_to "SignIn", new_user_session_path %></li>
      <% end %>
    </ul>
  </nav>
</div>

<style>
  .header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 0 20px;
    background-color: #f1f1f1;
  }

  .header_title {
    display: flex;
    align-items: center;
    gap: 20px;
  }
 
  .nav-links {
    display: flex;
    justify-content: space-between;
    align-items: center;
    gap: 20px;
  }

  .menu-button {
    display: none;
    border: none;
    font-size: 30px;
  }

  
   .header_title a {
     text-decoration: none;
     color: black;
   }

  .nav-links li {
    list-style: none;
  }

  .nav-links a {
    text-decoration: none;
    color: black;
    padding: 10px;
  }

  .nav-links a:hover {
    color: red;
  }

  /* Show nav links when screen is small */
  @media only screen and (max-width: 660px) {
    .header h1 {
      font-size: 20px;
    }

    .nav-links a {
    padding: 5px;
  }
  }

  @media only screen and (max-width: 360px) {
    .header {
      flex-direction: column;
      align-items: flex-start;
    }
  }

  @media only screen and (max-width: 290px) {
  .nav-links {
    display: hidden;
  }
 }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friends App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'layouts/header' %>
 <% if notice %>
  <%= render 'layouts/alert' %>
 <% end %>
    <div class="body">
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/hello.html.erb
<style>
.h1 {
  text-align: center;
  margin-top: 50px;
}

.ul {
  list-style: none;
  padding: 0;
  margin: 20px 0;
}

.ul li {
  margin-bottom: 10px;
}

.btn {
  display: inline-block;
  padding: 10px 20px;
  background-color: #007bff;
  color: #fff;
  text-decoration: none;
  border-radius: 5px;
}

.btn:hover {
  background-color: #0062cc;
  color: #fff;
}
</style>

<h1 class="h1">Welcome to My Friends!</h1>
<br>
<p>My Friends is a website that allows you to save and manage the contact and social media information of your friends. Here's what you can do:</p>

<ul class="ul">
  <li>Create an account or log in if you already have one</li>
  <li>Add your friends to your list</li>
  <li>View and edit the details of each friend</li>
  <li>Delete friends you no longer want to keep in your list</li>
  <li>Edit your own profile or delete your account</li>
</ul>
<br>

 <% if user_signed_in? %>
  <p>You are already logged in. Click the button below to view your friends list.</p>
  <br>
  <%= link_to "View your friends", friends_path, class: "btn btn-primary" %>
  <% else %>
  <p>Ready to get started? Click the button below to create your account or log in if you already have one.</p>
<br>
<%= link_to "Create an account or log in", new_user_registration_path, class: "btn btn-primary" %>
  <% end%>  